---
resource_group_name: "demoAKSLab"
aks_name: "myAKSCluster"
aks_location: "southeastasia"
k8s_version: "1.16.9"
username: "azureuser"
app_name: "app_demo"
tier: "frontend"
image: "calsaviour/thalestest:thalestest"
min_count: "1"
max_count: "2"
new_max_count: "3"
path: "/tmp/test"