- name: "...create aks using az cli"
  shell: >
        az aks create \
          --resource-group {{ resource_group }} \
          --name {{ aks_name }} \
          --node-count 1 \
          --enable-vmss \
          --enable-cluster-autoscaler \
          --min-count 1 \
          --max-count 3 \
          --kubernetes-version 1.13.5
  register: create_aks
  
- name: "...enable autoscaling"
  shell: >
        az aks update \
          --resource-group {{ resource_group }} \
          --name {{ aks_name }} \
          --enable-cluster-autoscaler \
          --min-count 1 \
          --max-count 3
  register: create_aks

- name: "...create aks using az cli"
  shell: >
        az aks update \
          --resource-group {{ resource_group }} \
          --name {{ aks_name }} \
          --update-cluster-autoscaler \
          --min-count 1 \
          --max-count 5
  register: create_aks
