apiVersion: v1
kind: Service
metadata:
  name: goapp-service
  labels:
    app: guestbook
spec:
  selector:
    app: goapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
